MyLibraryBooks/MyCinema/Pages/CreateFilm.cshtml.cs
using Library;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyCinema.Pages
{
    public class CreateFilmModel : PageModel
    {
        public LibraryDB context { get; private set; }

        public CreateFilmModel(LibraryDB db)
        {
            context = db;
        }

        public void OnPostAdd(Film f)
        {
            context.Films.Add(f);
            context.SaveChanges();
        }
    }
}

MyLibraryBooks/MyCinema/Pages/CreateSchedule.cshtml.cs
using Library;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MyCinema.Pages
{
    public class CreateScheduleModel : PageModel
    {
        public LibraryDB context { get; private set; }

        [BindProperty] public Schedule Schedule { get; set; }
            
        [BindProperty]
        public int film_id { get;set; }
        public CreateScheduleModel(LibraryDB db)
        {
            context = db;
        }

        public void OnPost()
        {
            Schedule.Film_id = context.Films.Find(film_id);
            context.Schedules.Add(Schedule);
            context.SaveChanges();
        }
    }
}

MyLibraryBooks/MyCinema/Pages/EditFilm.cshtml.cs
using Library;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyCinema.Pages
{
    [IgnoreAntiforgeryToken]
    public class EditFilmModel : PageModel
    {
        public LibraryDB context { get; private set; }
        public EditFilmModel(LibraryDB db)
        {
            context = db;
        }
        [BindProperty]
        public Film? film { get; set; }
        public void OnGet(int id)
        {
            film=context.Films.FirstOrDefault(x => x.Id == id);
        }

        public IActionResult OnPost()
        {
            context.Films.Update(film!);
            context.SaveChangesAsync();
            return OnPostCancel();
        }
        public IActionResult OnPostCancel()=> RedirectToPage("/Index");

    }
}

MyLibraryBooks/MyCinema/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MyCinema.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MyLibraryBooks/MyCinema/Pages/Index.cshtml.cs
using Library;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace MyCinema.Pages
{
    public class IndexModel : PageModel
    {
        public LibraryDB context { get; private set; }
        public IEnumerable<Schedule> ScheduleToday { get; set; } = null!;
        public IndexModel(LibraryDB db)
        {
            context = db;
        }

        public void OnGet()
        {
            ScheduleToday = GetTodayFilms();
        }

        public IEnumerable<Schedule> GetFilm(Film film)
        {
            var t = ScheduleToday.Where(s => s.Film_id.Id == film.Id).ToList();
            return t;
        }

        public IActionResult OnPost(int id)
        {
            context.Schedules.RemoveRange(context.Schedules.Where(sc=>sc.Film_id.Id==id));
            context.SaveChanges();
            ScheduleToday = GetTodayFilms();
            return Page();
        }

        private IEnumerable<Schedule> GetTodayFilms()
        {
            string date = DateTime.Today.ToString("yyyy-MM-dd");

           return context.Schedules.Include(c => c.Film_id).Where(s => s.Date == date).ToList();
        }
        public void OnPostSearch(string word)
        {
            ScheduleToday = String.IsNullOrEmpty(word)
                ? GetTodayFilms()
                : GetTodayFilms().Where(sc => sc.Film_id.Title.Contains(word));
        }
    }
}

MyLibraryBooks/MyCinema/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyCinema.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MyLibraryBooks/MyCinema/Pages/CreateFilm.cshtml
@page
@model MyCinema.Pages.CreateFilmModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyCinema.styles.css" asp-append-version="true" />
</head>
<body>
<main>
    <div class="mybody">
        <div id="home"><a asp-area="" asp-page="/Index">Home</a></div>

        <div id="modal-window">
            <div id="details">
                <div class="load"></div>
                <a href="#" id="close" onclick="closeModalWindow(event)">❌</a>
                <form method="post">
                    <input type="hidden" name="poster" id="film-poster"/>
                    <input type="hidden" name="title" id="film-title"/>
                    <input type="hidden" name="released" id="film-released"/>
                    <input type="hidden" name="genre" id="film-genre"/>
                    <input type="hidden" name="country" id="film-country"/>
                    <input type="hidden" name="director" id="film-director"/>
                    <input type="hidden" name="writer" id="film-writer"/>
                    <input type="hidden" name="actors" id="film-actors"/>
                    <input type="hidden" name="awards" id="film-award"/>
                    <input type="submit" value="add DB" asp-page-handler="add" id="addFilm"/>
                </form>
            </div>
        </div>
        <h2>Search</h2>
        <input type="text" name="API_key" id="API_key" placeholder="API key">
        <div class="movie-search">
            <b>Title:</b>
            <input type="text" name="title" id="title">
            <br>
            <b>Type:</b>
            <select name="type" id="type">
                <option value="movie">Movie</option>
                <option value="series">Series</option>
                <option value="episode">Episode</option>
            </select>
            <br>
            <input type="button" value="Search" id="search">
        </div>
        <div id="result">
            <h2>Films</h2>
            <img src="ZZ5H.gif" alt="" class="load">
            <div id="films"></div>
            <input type="button" value="More" id="moreFilms">
        </div>
    </div>
   
</main>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/js/script.js" asp-append-version="true"></script>
</body>
</html>

MyLibraryBooks/MyCinema/Pages/CreateSchedule.cshtml
@page
@using System.Collections
@using System.Runtime.Serialization
@using Library
@model MyCinema.Pages.CreateScheduleModel
@{
    IEnumerable<Film> films = Model.context.Films.ToList();
}
<form method="post" id="form-schedule">
    <input type="date"  asp-for="Schedule.Date" value="@DateTime.Now.ToString("yyyy-MM-dd")"/><br/>
    <input type="time" asp-for="Schedule.Time" value="@DateTime.Now.ToShortTimeString()"/><br/>
    <select asp-for="film_id"><br/>
        @foreach (Film f in Model.context.Films)
        {
            <option value="@f.Id">@f.Title, @f.Released</option>
        }
    </select>
    <br/><input type="submit"/><br/>
</form>

MyLibraryBooks/MyCinema/Pages/EditFilm.cshtml
@page "{id:int}"
@model MyCinema.Pages.EditFilmModel
<div class="edit-film">
    <form method="post">
        <p>Poster:</p>
        <input type="text" asp-for="film.Poster"/>
        <p>Title:</p>
        <input type="text" asp-for="film.Title"/>
        <p>Released:</p>
        <input type="text" asp-for="film.Released"/>
        <p>Genre:</p>
        <input type="text" asp-for="film.Genre"/>
        <p>Country:</p>
        <input type="text" asp-for="film.Country"/>
        <p>Director:</p>
        <input type="text" asp-for="film.Director"/>
        <p>Writer:</p>
        <input type="text" asp-for="film.Writer"/>
        <p>Actors:</p>
        <input type="text" asp-for="film.Actors"/>
        <p>Awards:</p>
        <input type="text" asp-for="film.Awards"/>
        <input type="hidden" asp-for="film.Id"/><br/>
        <input type="submit" value="Ok" asp-page-handler="Ok"/>
        <input type="submit" value="Cancel" asp-page-handler="Cancel"/>
    </form>
</div>

MyLibraryBooks/MyCinema/Pages/Index.cshtml
@page 
@model IndexModel
@{
    var d = DateTime.Today.ToString("yyyy-MM-dd");
}

<div class="text-center myheader">
    <h1 class="display-4">Welcome</h1>
    <p>My Cinema.</p>
</div>
<form id="search" method="post">
    <input type="text" name="word" id="fiel-search" placeholder="Search..."/>
    <input type="submit" value="🔎"  asp-page-handler="Search"/>
</form>
<div id="modal-window">
    <div id="details">
        <div class="load"></div>
        <a href="#" id="close">❌</a>
        <img src="" alt="" id="poster">
        <table>
            <tr>
                <th>Title:</th>
                <td id="titli"></td>
            </tr>
            <tr>
                <th>Released</th>
                <td id="released"></td>
            </tr>
            <tr>
                <th>Genre</th>
                <td id="genre"></td>
            </tr>
            <tr>
                <th>Country</th>
                <td id="country"></td>
            </tr>
            <tr>
                <th>Director</th>
                <td id="director"></td>
            </tr>
            <tr>
                <th>Writer</th>
                <td id="writer"></td>
            </tr>
            <tr>
                <th>Actors</th>
                <td id="actors"></td>
            </tr>
            <tr>
                <th>Award</th>
                <td id="award"></td>
            </tr>
        </table>
    </div>
</div>
<div id="films">
    @if (Model.ScheduleToday.Count() == 0)
    {
        <h2 class="title">There are no sessions today</h2>
    }
    else
    {
        @foreach (Film f in Model.context.Films)
        {
            if (Model.GetFilm(f).Count() != 0)
            {
                <div class="infofilm">
                    <div class="opacity-background"></div>
                    <form method="post" class="form-delete">
                        <input type="hidden" name="id" value="@f.Id"/>
                        <input type="button" class="isDelete" value="🗑️"/>
                        <div class="delete-window">
                            <div class="delete">
                                <label class="message">Delete ?</label><br/>
                                <input type="submit" class="messagebtn" value="Yes"/>
                                <input type="button" class="no-delete messagebtn" value="No"/>
                            </div>
                        </div>
                    </form>
                    <div class="film">
                        <img src="@f.Poster" alt="Poster">
                        <p class="title">@f.Title</p>
                        <p class="year">@f.Released</p>
                        <button class="select-film-details">Details</button>
                        <input type="hidden" class="select_film_poster" value="@f.Poster"/>
                        <input type="hidden" class="select_film_title" value="@f.Title"/>
                        <input type="hidden" class="select_film_released" value="@f.Released"/>
                        <input type="hidden" class="select_film_genre" value="@f.Genre"/>
                        <input type="hidden" class="select_film_country" value="@f.Country"/>
                        <input type="hidden" class="select_film_director" value="@f.Director"/>
                        <input type="hidden" class="select_film_writer" value="@f.Writer"/>
                        <input type="hidden" class="select_film_actors" value="@f.Actors"/>
                        <input type="hidden" class="select_film_awards" value="@f.Awards"/>
                        <a asp-page="EditFilm" asp-route-id="@f.Id">Edit</a>
                    </div>
                    <div class="schedule">
                        <h3>Time:</h3>
                        @foreach (var s in Model.GetFilm(f))
                        {
                            <p>@s.Time</p>
                        }
                    </div>
                </div>
            }
        }
    }
</div>